name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Display .env file
      #   run: |
      #     echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE}}" >> .env
      #     echo "MYSQL_USER=${{ secrets.MYSQL_USER}}" >> .env
      #     echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD}}" >> .env
      #     echo "MYSQL_PORT=${{ secrets.MYSQL_PORT}}" >> .env
      #     echo "MYSQL_HOST=${{ secrets.MYSQL_HOST}}" >> .env
      #     echo "DB_DIALECT=${{ secrets.DB_DIALECT}}" >> .env
      #     cat .env

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -u ${{secrets.MYSQL_USER}} -p"${{secrets.MYSQL_PASSWORD}}"

      - name: Run Tests
        run: npm test
